- name: this playbook is to test the debug message
  hosts: nginx
  become: yes
  
  tasks:
    - name: print the message
      ansible.builtin.debug:
        msg: "my name is {{name}}: i am from {{district}}"