- name: this playbook is to test the debug message
  hosts: nginx
  become: yes
  vars:
    name: vasim
    state: NELLORE
    website: https://www.joindevops.com/batch-74s'
    greeting: hi my name is, vasim
  tasks:
  - name: this task is to convert lower case into upper case
    ansible.builtin.debug:
      msg: "{{ name | upper }}"
      

  - name: this task is to convert lower case into upper case
    ansible.builtin.debug:
      msg: "{{ state | lower }}"

  - name: split url into hostname
    ansible.builtin.debug:
      msg: "{{ website | urlsplit('hostname') }}"
  
  - name: split the data
    ansible.builtin.debug:
      msg: "{{ greeting | split(',') }}"