- name: this playbook is to test the debug message
  hosts: nginx
  become: yes
  
  tasks:
  - name: this task is to convert lower case into upper case
    ansible.builtin.debug:
      msg: "{{vasim | VASIM}}"
      