- name: this playbook is to test the debug message
  hosts: nginx
  become: yes
  vars:
    name: vasim
    state: NELLORE
  tasks:
  - name: this task is to convert lower case into upper case
    ansible.builtin.debug:
      msg: "{{ name | upper }}"
      

  - name: this task is to convert lower case into upper case
    ansible.builtin.debug:
      msg: "{{ state | lower }}"

  - name: split url into hostname
    ansible.builtin.debug:
      msg: "{{ http://user:password@www.acme.com:9000/dir/index.html?query=term#fragment | urlsplit('hostname') }}"