- name: this playbook is to test the debug message
  hosts: nginx
  become: yes
  vars:
    name: vasim
    state: NELLORE
  tasks:
  - name: this task is to convert lower case into upper case
    ansible.builtin.debug:
      msg: "{{ name | upper }}"
      

  - name: this task is to convert lower case into upper case
    ansible.builtin.debug:
      msg: "{{ state | lower }}"